### ISSUE TITLE
Licode does not work with Ionic and webview crosswalk

### ISSUE THREAD

**Issue by evilword666** [lynckia/licode#1013]
I have a Licode installation and this works fine in the browser but when I try to open this in an Ionic WebView crosswalk this does not work, that show me a white page but I can only see the control buttons, I can´t obtain the screen visualization. 

![blank](https://user-images.githubusercontent.com/10425457/29637831-00e2e668-881b-11e7-97fb-e08b2ba46cb5.png)

I'm using the web view crosswalk to access in my ionic application. Previously that plugin worked fine to me and I could open my Licode page with my cellphone using the web view.  Recently I needed to format my server and I reinstalled everything. However, after cloning the project and installing the application as indicated by the official page, my Licode project is no longer available to show into the web view, the android debugger shows me the following error, that error didn’t appear before only until this last update of the project.

![errorrr](https://user-images.githubusercontent.com/10425457/29637906-36939596-881b-11e7-91c9-31e3a575e144.png)

Could there be a change in the last update that prevents now that I can view my project in the webview of my application Ionic?

**Comment by jcague** [comment]
please use the issue template we provide when you create a new issue, thanks!

**Comment by evilword666** [comment]
Hi @jcague, could you tell me if you need more details?
I think that what I wrote the problem is understandable.

**Comment by jjahifi** [comment]
@evilword666 , Crosswalk is an abandoned project. It is unlikely to be up-to-date or even compatible in near future.
https://crosswalk-project.org/blog/crosswalk-final-release.html
Apache Cordova Android is, at least in my experience, completely compatible with Chrome/Chromium (it actually shares code with Chromium). I would suggest changing the tool.

Actually I do not think that your problem is related to Licode. The errors are more likely due to a badly configured Content Security Policy.

**Comment by evilword666** [comment]
Thanks @jjahifi  I solved my problem updating to the last version of crosswalk
