### ISSUE TITLE
Unable to connect to erizo_controller using IP address over wss://

### ISSUE THREAD

**Issue by arsenicraghav** [lynckia/licode#1108]
**Description**

When I try to establish a wss:// connection to erizo_controller using the IP address received in the Token, I get an error and not able to establish a secure socket connection. 

**Steps to reproduce the issue:**
1. Try connecting to erizo_controller over wss:// and the IP address
2. Keep the erizo_controller's host-name field empty.

**Describe the results you received:**
'wss://x.y.z.p:8080/socket.io/?EIO=3&transport=websocket' failed: **Error in connection establishment: net::ERR_INSECURE_RESPONSE** 

**Describe the results you expected:**
Expected a successful websocket connection to erizo_controller

**Additional information you deem important (e.g. issue happens only occasionally):**

Is it mandatory to use host name for wss:// if so, how do I get to scale the Controller when IP address will be assigned on the fly and may not necessarily have a host-name with certificate and all configured  ? 
**Licode commit/release where the issue is happening**

**Additional environment details (Local, AWS, Docker, etc.):**

**Comment by iamnibin** [comment]
Did you give the proper certificate?

Seems like certificate issue.

**Comment by arsenicraghav** [comment]
@iamnibin yes, proper certificates are in place.

**Comment by iamnibin** [comment]
erizo controller public ip should be the domain of certificate which you are using. 
example you have certificate of *sample.com* the  public ip of erizo controller will be *sample.com* / *subdomain.sample.com*

to make the current system work 
https://x.y.z.p:8080 
this will give an ssl error. 
Goto advanced and confirm security exception.

This will make it work

**Comment by arsenicraghav** [comment]
I hope you are not using the term host-name and IP address interchangeably. I am aware about the jazz you have mentioned in your comment but would request you to go through the my description.

**Comment by kekkokk** [comment]
you cannot establish a secure connection to an ip.
chrome allows you to do it only in 127.0.0.1
You need to set up a certificate for that specific ip or you have to put the certificate domain in erizoController.host
Remember to delete all the old tokens from the mongo db in order to generate new tokens with the newly created address wss://hostname.domain.com:8080

**Comment by arsenicraghav** [comment]
@kekkokk Thank you for confirming my doubt. If that is the case then how do you establish secure connection to dynamically added new erizoControllers with random IP addresses for scaling purposes and these dynamically allocated IPs are not tied to any domain name in advance. Can you throw light on that ?

**Comment by kekkokk** [comment]
unfortunately I didn't a find a solution yet and I'm stuck at this point too. My option right now is to have only one controller since is enough for me.
maybe @lodoyun can explain to us how to properly scale a controller.

I really can't figure out a solution.
Maybe one option is to deploy the controllers under one load balancer, then add a param to the token used by LB to select at which controller forward the request.
But I'm totally out of knowledge about LB and sure there's a better way.

**Comment by yuwenyin** [comment]
@kekkokk I face the same problem recently,how to deploy licode on server cluster
and I have two thoughts,one is totally LB and the other is controlling it by logical layer.
I create logical room in business logic and I just need to ensure people in the same room connected to the same server.so I can deploy many independent licode service and make LB by room level.
I want to try the second (╯◕◞౪◟◕‵)╯

**Comment by kekkokk** [comment]
yeah but still the problem of the certificate remains.
You can use nuve to make business logic and assign certain specific controller, but you cannot spawn them programmatically. for a correct ssl connection each of them must have a valid domain with a valid certificate

**Comment by yuwenyin** [comment]
@kekkokk agree

**Comment by alokp** [comment]
Our setup is kind of like this

Load Balancer - Web servers - Erizo controllers
                                   |
                               Nuve

When web server gets the token from Nuve it adds a new field to it and copies the address of erizo controller into the new field and the load balancer is set as the host. The web server runs a socket.io server which receives the request from the erizo client (after passing thru the LB) and get the erizo controller field from the injected field. It then restores the token to its original state (or the signature won't match) and initiates a socket.io connection with the intended erizo controller, thus acting like a socket.io pass-thru proxy. Hacky but works :)

**Comment by arsenicraghav** [comment]
@alokp what do mean by webservers ? Socket Connections are direct in nature, not sure how you will proxy them especially with socket.io ?

**Comment by alokp** [comment]
@arsenicraghav I have a bunch of express (node.js) web servers that serve our website. These web servers run behind a load balancer. We also have a bunch of Erizo controllers that nuve selects in a round-robin fashion. The express web servers also run socket.io servers. Since we manipulate the token to have our load balancer as the host, erizo clients send the socket.io connection request to the load balancer. The load balancer passes that to one of the web servers running socket.io server. Socket.io server gets the erizo controller info from the manipulated token, restores the token to its original form and makes a socket.io connection to the relevant erizo controller. At that point my web server has a connection with both the erizo client (as socket.io server) and the erizo controller (as socket.io client) and forwards the messages sent be either one to the other, thus acting like a sort of passthru proxy.
