### ISSUE TITLE
Migrate to Socket.io 1

### ISSUE THREAD

**Issue by mkhahani** [lynckia/licode#476]
Is there any plan to migrate to **Socket.io 1**. The current version (0.9.6) is really old and there are many advantages using version 1:
- New engine
- Binary support
- Automated testing
- Scalability
- Integration
- Better debugging
- Streamlined APIs
- CDN delivery
- Future innovation

You can see the full description [here](http://socket.io/blog/introducing-socket-io-1-0).

**Comment by fabio-rigato** [comment]
Any news about it?

**Comment by kekkokk** [comment]
I think that the imminent version-bump of licode, should consider switching to new socket.io
the main reason that was not implemented yet I think to comprehend that it's due to backward compatibility. but there are soooo many changes from the past that probably some other things other than socket will not work if you have an ~1yr old version.

**Comment by mkhahani** [comment]
@kekkokk is right. The compatibility considerations are not valid any more. What is preventing us from upgrading?

> we are using new socket in production since january and no problem yet

Do you any patch for that?

**Comment by kekkokk** [comment]
not yet, our branch deviated so much from the current that is really difficult to make a patch but i'll look into it as soon as possible
