### ISSUE TITLE
openssl DTLS  Handshake failed

### ISSUE THREAD

**Issue by xuhongming251** [lynckia/licode#555]
hi , I use erizo.so + node js .

nodejs + node-gyp addon + erizo.so

I compile node js 0.10.47 shared link to openssl. and erizo.so use the same version openssl .

I have tested the openssl all the version 1.0.\* ，openssl-1.0.2a 、openssl-1.0.2e、openssl-1.0.2k、openssl-1.0.2l、openssl-1.0.2i、openssl-1.0.2j、openssl-1.0.2u。

but they do not work very well.
1、openssl-1.0.2u、openssl-1.0.2l：
 sometimes，it occurs SSL3_GET_CERT_VERIFY:bad ecdsa signature， so Handshake failed。
2、
openssl-1.0.2a 、openssl-1.0.2e
Handshake failed all the time.

erizo run env：
ubuntu 14.04 LTS

brower env：

google chrome 53.0.2785.116 (64-bit)

**Comment by xuhongming251** [comment]
Handshake failed:
1、erizo create offer ，modify sdp a=sendrecv instead of a=recvonly.
2、exchange signnaling message

but this is ok:
1、browser create offer ，modify sdp a=sendrecv instead of a=sendonly.
2、exchange signnaling message

I donot why erizo crate offer  often a problem,but other peer offer first is ok.

**Comment by jcague** [comment]
I'd recommend node v0.10.37 and openssl 1.0.1l. They work well in our machines.

**Comment by xuhongming251** [comment]
I modify the licode offer sdp , and add a=setup:actpass. now all is ok . have resolved  dtls handshake failed  error , this error have not appear again , thx~!

**Comment by kekkokk** [comment]
@jcague I am getting this error quite often with a clean install from actual master branch
`[erizo-636dc816-7fc7-a590-39a4-994bde409c8f] 2017-02-16 11:19:00,882  - WARN [0x7f91deffd700] DtlsTransport - id: iPrlVcOP8IScztlbk1dv_465085895674250300, type: subscriber,  message: Handshake failed, transportName:video, openSSLerror: Dtls Timeout on Resender`

this is happening especially in a many to many scenario, when the subscriber has lots of video to subscribe.
I reproduce the issue with a remote ec2 instance, ubuntu 14.04.5 LTS.
I have two computers, attached to 2 different connections. I open 3 tabs of the basicexample in one pc, and one in the other. I keep reloading the one with only one tab, and often one ore more video fails to subscribe. i get the spinning icon and about 2 minutes later the stram-failed event.

an `openssl version` command on the server give me `OpenSSL 1.0.1f 6 Jan 2014`

Again, it's a clean install. I wanted to know if there's anything I can to to try to reduce the number of failed connections and address the issue. 
also, the stream failed message came up about 2 minutes after the stream-subscribed event and it's very annoying. tried to revert to the suggested openssl 1.0.1l but i think it's not compatible with node 6.9.2 used by nvm. the result is a crash on start of the erizoJS.

**Comment by kekkokk** [comment]
also reproducible opening some (5/6) tabs on the same machine and keep reloading one until the problem occurs

**Comment by lodoyun** [comment]
Basically that timeout is fired when Chrome is not answering the DTLS messages in the handshake. I'm not saying there can't be an issue somewhere in the code  but it may very well be a client-side thing in many cases.
Rate controlling the subscriptions in your client is a good way to prevent this. Also, listening to the stream-failed event will let you know when to retry a subscription.
In any case we will investigate this further.

**Comment by kekkokk** [comment]
listening the stream-failed it's ok but it's fired sometimes 2 minutes later. the user experience isn't so good.
I just noticed one interesting pattern: I joined a room with 5 streams being published;
the first subscribe went stuck with the spinning icon and the consecutive 4 went smooth.
So, I waited about 1 min and the video was still stuck in loading.
so I unsubscribed the 4 videos which succedeed, and suddently the stuck video connected.
It's like the dtls messages are not mapped to the stream. 
I don't know how to explain very well, but i'm trying to do more tests to be more specific

**Comment by kekkokk** [comment]
Did some new tests but nothings changes, also with ubuntu 16. it starts behaving wrong when I open the 4th tab with basicexample. digging in the problem (reading jnoring thougths on the licode issues over dtls) seems related to a packet loss issue and it makes sense. 

@lodoyun have you read [bugs.chromium.org](https://bugs.chromium.org/p/webrtc/issues/detail?id=4403) ? 

my capabilities are far from understanding this but seems that licode is handling something wrong.
I continue to see this as a priority, 'cause on an ubuntu ec2 vanilla machine, a many-to-many whith 4+ people scenario is not "reliable" atm. the fail rate is very high. i tried all openssl versions and also the latest libnice but without success.

**Comment by jcague** [comment]
I'm not able to reproduce your problem locally. And we're also running rooms with 20+ participants in production without this issue, so I'm not sure it it's something general. In your tests all the participants run from the same machine and browser, so it could cause DTLS to timeout due to different reasons (CPU, bandwidth, etc.). 

can you run the same test by joining participants from different machines?

**Comment by kekkokk** [comment]
I think it's a packet loss issue so locally neither I am able to reproduce. but when I deploy licode (master branch), in a ubuntu 14.04 vanilla on amazon, and try to join with 4+ users, some subscribe actually fails. sometimes the failed event isn't fired.
Tried with one, two, three and also four different machines. the behaviour is the same. Probably an mtu issue? I really don't know. 

I managed to lower the retries in the DTLS transport to 2 times and moved the `rtp_resender_->cancel(); and 
rtcp_resender_->cancel();` into the handshakecompleted block, so now the fail event is "reliable".
I think that in the actual implementation the resender->cancel() is fired when a dtls packet is received, but what if the "last flight" was broken in two packets and the second one is lost? we cancel the resend, and the connection is never established, neither the fail event is fired.

I think there's something "wrong" in the code. With some internet connections this is more evident than others. With my office connection seems more hard to break, but with my home connection the fail rate is very high. and waiting 2 minutes for the stream-failed event, in a production environment is not "acceptable" in my opinion.

I can manage to let you access to my ec2-ami or... idk, I'm available for any type of test. 
I think the issue is a long date issue and have never really been fixed, cause a lot of users opened an issue about that.  It's also very difficult to reproduce and track and I don't have the skill to dig more :(

**Comment by kekkokk** [comment]
@jcague I made a simple video (sorry for the quality) 
[YoutTube](https://www.youtube.com/watch?v=Bt3cNpgZpZE)
00:15 - 3 computers connected. everything's ok
00:18 - reload second pc -> 1 and 3 can't subscribe to the stream
00:45 - reload 1 pc -> it subscribe to all streams. 3rd pc still can't subscribe to the previous.
01:00 - 01:45  reload randomly, everything's ok
01:45 - reload 1. it can't subscribe to one of the others video. 
Decided to wait. sorry for the unreadable console, nothing special in there. from webrtc internals we can see empty graphics and ice connection state = complete.
3:56 - we get the stream-failed
4:05 - reload and everything's ok
4:17 - reload mid and again 1 and 3 can't subbscribe
from there did other random reload and it behaves totally random.
as you can see the fail rate is very high

is there anything I can do to help you?

**Comment by kekkokk** [comment]
@jcague @lodoyun any update on this side? 
I updated my prod branch to the current master. still, the issue exist when in a network with high pl/congestion.
(tried with v2 vanilla also).
simply connect in two different network (one 100/100 mbit and the other 20/1mbit) and open 8 basicexample tab on 2 different pcs (each connected to one different network).
so we have 4 tab on pc1 and 4 tab on pc2.
try to randomly reload one of these tab and see that the infinite load spinning icon appears on some subscribed streams. It happens more frequently on the "worst network pc".
I need to use the "patch" that I posted 2 message before to be able to manage my frontend in a reliable way. 
I suggest to merge it in master branch until you investigate more into the problem (which I consider very serious). Tried this many times in many different conditions (network, pc, os).
we are handling wrong the resend of the last flight packet.
If you are interested I can make a PR. 
I am sure we will all benefit.
