### ISSUE TITLE
Heavy CPU usage -> erizojs timeout

### ISSUE THREAD

**Issue by kekkokk** [lynckia/licode#924]
Hi guys, 
I'm doing some stability tests for the entire platform, and I noticed that in a 1 core server, when 7+ users joined, sometimes erizojs crash, timed out and close connections.

So I took Licode and deployed to an EC2 t2.xlarge with 4 cores, started a basicexample and let 25 people join it.
everyone's streaming 640x480 with 2000 kbit cap (NO SIMULCAST).

It goes well for about 5 min (70% avg. cpu, seriously?), sometimes more sometimes few and then a CPU spike crashes the entire process.

Is it normal? I don't remember very well but 1 year ago I did the same tests and if I remember correctly I could join way more people with no problems. note that i was NOT recording, only sfu.

Also note that I was using only 1 erizojs process.
Finally, when I close all browsers at once,
for about one minutes the cpus is stuck like this:
![screen shot 2017-06-20 at 6 54 32 pm](https://user-images.githubusercontent.com/15072723/27345486-26c8ab0a-55ea-11e7-9f5b-0fcc95387228.png)

Seems like it is draining the queues.
Seems a bit resources demanding for only 25 people.

Have you done some similar stress tests and noticed the same behaviours?
Is there anything I can do on the os (Ubuntu 14 lts) to tune it for these specific tasks?

Is there any tools I can use to profile and locate the bottleneck?

Any info appreciated

**Comment by lodoyun** [comment]
@kekkokk We appreciate the comment but since we recently introduced an issue template, could you use it?   It's particularly important to know the commit you're using, and wether you're using the docker image or not.

We're tweaking a number of things that could affect performance and are solving a number of crashes, particularly for NiceR, so expect improvements there. If you could provide more information about the crash we will investigate it.

Regarding performance, keep in mind 25 participants in the basic example means (25^2 = 625) connections to licode. And if they manage to send 2 Mbps, you would have 625*2Mbps is 1.25 Gbps, that's quite a lot of traffic and you will need big boxes (servers) for that. Also, each client would be receiving 24*2 = 50Mbps ideally. In other words, capping the bitrate to 500kbps you would be able to fit 144 rooms with 25 participants, again, ideally (there are other factors involved).

Bitrate in and out of the server is a really important factor and you have to measure it in your experiments.  

t2 instances provide CPU bursts, for Licode you're going to need sustained CPU performance. Bursts will add variability to the test.

For that amount of connections you're testing there, you will get a better experience with more erizoJS processes (around 10 should be fine).

Again, We're currently busy using spine to stress Licode servers. While we've fixed a number of crashes, we haven't noticed any significant increase in CPU use.

**Comment by kekkokk** [comment]
Thanks for your complete answer and sorry for the template. I used to use it but today I probably felt lazy.

You made the point in lots of things I haven't considered!
There are instanceType you suggest that are more suitable for Licode? like the C ones?

Appreciate your help,
have a great day!

[off topic]
[Discourse](http://discourse.lynckia.com/t/is-licode-h264-ready/513)
