### ISSUE TITLE
Spine Test. How it works?

### ISSUE THREAD

**Issue by kekkokk** [lynckia/licode#929]
**Description**

Hello again guys,
I'm trying to use Spine but I can't find any info on how to use it.
Can you briefly explain us how it works?

**Steps to reproduce the issue:**
1.   cd licode/spine
2.   ./installSpine.sh
3.   try to run every .js file in spine folder with node, starting from `node runSpineClients.js`

**Describe the results you received:**

`module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: liberizo.so: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/licode/spine/nativeClient.js:2:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
`

**Describe the results you expected:**

Idk

**Additional information you deem important (e.g. issue happens only occasionally):**

The project is correctly built, I can make erizo work and use basicexample with no probl.

**Licode commit/release where the issue is happening**

ee36400b6598d03e5c02f79738c1f8cc555d5418

**Additional environment details (Local, AWS, Docker, etc.):**

EC2 instance

**Comment by kekkokk** [comment]
@lodoyun !up

**Comment by lodoyun** [comment]
In order to run it you need to:
- set up the `LD_LIBRARY_PATH` so it includes the location of liberizo.so, usually `licode/erizo/build/erizo`
- make sure you are using node 6, running `nvm use` should take care of that. If you don't have nvm in your system you can run licode's by doing `. path_to_licode/build/libdeps/nvm/nvm.sh`

Then make sure `spineClientsConfig` is pointing to your basicExample. The config file is pretty self-explanatory, just note that, the file by default overwrites some values, if you want to stream from a file you should leave only `video` with the file in `publishConfig` (or put it after the other `video`) same thing with `subscribeConfig`.
Also, this will all run in one process, so if you want to run a lot of connections it's advisable to start several spine processes with a fraction of the desired connections

**Comment by kekkokk** [comment]
many thanks!
